<?php
/**
 * @file
 * Module file.
 */

/**
 * Implements hook_theme().
 */
function contact_social_theme($existing, $type, $theme, $path) {
  return array(
    'contact_social' => array(
      'variables' => array(

        'align' => 'right',
        'class' => array('contact_social'),
        'top' => '40%',
		'twitter_image' => base_path() . drupal_get_path('module', 'contact_social') . '/contact_social.png',
		
		'twitter_title' => t('Join our group LinkedIn'),
        'twitter_height' => '35px',
        'twitter_width' => '35px',
		'twitter_link' => 'http://www.linkedin.com/groups/Brazilian-Chamber-Commerce-in-Great-2578992/about',
		
		'facebook_title' => t('Like us on Facebook'),
        'facebook_height' => '35px',
        'facebook_width' => '35px',
		'facebook_link' => 'https://www.facebook.com/Brazilianchamberofcommerceingreatbritain',
		
		'contact_us_title' => t('Contact us'),
        'contact_us_height' => '100px',
        'contact_us_width' => '35px',
		'contact_us_link' => 'contact',
		
        'enabled' => true,
      ),
      'template' => 'contact_social',
    ),
  );
}

/**
 * Implements hook_preprocess_contact_social().
 */
function contact_social_preprocess_contact_social(&$variables) {
  // Hide the tab when on the $link page.
  if (current_path() == $variables['contact_us_link']) {
    $variables['enabled'] = false;
  }
  // Allow Drupal to apply base_path and locale prefix outside of the
  // theme registry cache.
  $variables['contact_us_link'] = url($variables['contact_us_link']);
}

/**
 * Implements hook_init().
 */
function contact_social_init() {
  drupal_add_css(drupal_get_path('module', 'contact_social') . '/contact_social.css');
}

/**
 * Implements hook_footer().
 */
function contact_social_page_alter(&$page) {
  $page['page_bottom']['contact_social'] = array(
    '#type' => 'markup',
    '#markup' => theme('contact_social'),
  );
}
